import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.css']
})
export class BookComponent implements OnInit{
   books: string[] = [
    'To Kill a Mockingbird by Harper Lee',
    '1984 by George Orwell',
    'Pride and Prejudice by Jane Austen',
    'The Great Gatsby by F. Scott Fitzgerald',
    'Moby Dick by Herman Melville',
    'Jane Eyre by Charlotte Brontë',
    'One Hundred Years of Solitude by Gabriel Garcia Marquez',
    'The Catcher in the Rye by J.D. Salinger',
    'War and Peace by Leo Tolstoy',
    'The Lord of the Rings by J.R.R. Tolkien',
    'Animal Farm by George Orwell',
    'Brave New World by Aldous Huxley',
    'The Hobbit by J.R.R. Tolkien',
    'Fahrenheit 451 by Ray Bradbury',
    'The Chronicles of Narnia by C.S. Lewis',
    'Gone with the Wind by Margaret Mitchell',
    'The Grapes of Wrath by John Steinbeck',
    'Catch-22 by Joseph Heller',
    'Lord of the Flies by William Golding',
    'Wuthering Heights by Emily Brontë',
    'The Scarlet Letter by Nathaniel Hawthorne',
    'Don Quixote by Miguel de Cervantes',
    'The Odyssey by Homer',
    'The Iliad by Homer',
    'Crime and Punishment by Fyodor Dostoevsky',
    'Anna Karenina by Leo Tolstoy',
    'Les Misérables by Victor Hugo',
    'Pride and Prejudice by Jane Austen',
    'Great Expectations by Charles Dickens',
    'Frankenstein by Mary Shelley',
    'Dracula by Bram Stoker',
    'The Picture of Dorian Gray by Oscar Wilde',
    'Moby-Dick by Herman Melville',
    'The Adventures of Sherlock Holmes by Arthur Conan Doyle',
    'The Count of Monte Cristo by Alexandre Dumas',
    'The Brothers Karamazov by Fyodor Dostoevsky',
    'The Stranger by Albert Camus',
    'The Sun Also Rises by Ernest Hemingway',
    'For Whom the Bell Tolls by Ernest Hemingway',
    'The Old Man and the Sea by Ernest Hemingway',
    '1984 by George Orwell',
    'Animal Farm by George Orwell',
    'The Great Gatsby by F. Scott Fitzgerald',
    'Brave New World by Aldous Huxley',
    'To Kill a Mockingbird by Harper Lee',
    'The Catcher in the Rye by J.D. Salinger',
    'Lord of the Flies by William Golding',
    'One Hundred Years of Solitude by Gabriel Garcia Marquez',
    'Love in the Time of Cholera by Gabriel Garcia Marquez',
    'Midnight\'s Children by Salman Rushdie',
    'The God of Small Things by Arundhati Roy',
    'The Alchemist by Paulo Coelho',
    'Life of Pi by Yann Martel',
    'The Kite Runner by Khaled Hosseini',
    'A Thousand Splendid Suns by Khaled Hosseini',
    'The Book Thief by Markus Zusak',
    'The Road by Cormac McCarthy',
    'American Gods by Neil Gaiman',
    'The Name of the Wind by Patrick Rothfuss',
    'The Wise Man\'s Fear by Patrick Rothfuss',
    'A Game of Thrones by George R.R. Martin',
    'Harry Potter and the Sorcerer\'s Stone by J.K. Rowling',
    'Harry Potter and the Chamber of Secrets by J.K. Rowling',
    'Harry Potter and the Prisoner of Azkaban by J.K. Rowling',
    'Harry Potter and the Goblet of Fire by J.K. Rowling',
    'Harry Potter and the Order of the Phoenix by J.K. Rowling',
    'Harry Potter and the Half-Blood Prince by J.K. Rowling',
    'Harry Potter and the Deathly Hallows by J.K. Rowling',
    'The Hunger Games by Suzanne Collins',
    'Catching Fire by Suzanne Collins',
    'Mockingjay by Suzanne Collins',
    'Divergent by Veronica Roth',
    'Insurgent by Veronica Roth',
    'Allegiant by Veronica Roth',
    'The Maze Runner by James Dashner',
    'The Scorch Trials by James Dashner',
    'The Death Cure by James Dashner',
    'The Kill Order by James Dashner',
    'The Girl on the Train by Paula Hawkins',
    'Gone Girl by Gillian Flynn',
    'The Da Vinci Code by Dan Brown',
    'Angels & Demons by Dan Brown',
    'The Lost Symbol by Dan Brown',
    'Inferno by Dan Brown',
    'Origin by Dan Brown',
    'The Help by Kathryn Stockett',
    'The Fault in Our Stars by John Green',
    'Paper Towns by John Green',
    'Looking for Alaska by John Green',
    'Turtles All the Way Down by John Green'
  ];
  
  ngOnInit(): void {
      
  }
  

}
